### ISSUE TITLE
Last graphs cut off in shared dashboards 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1639] opened 2018-09-05 07:40 UTC
# Problem or idea
*What is the cause?*

The last visualisation in a shared dashboard appears cut off and you cannot see the full visualisation. 

Example dashboard on demo: https://demo.akvolumen.org/s/gXwCdv1tp-g

<img width="1261" alt="screen shot 2018-09-05 at 09 39 34" src="https://user-images.githubusercontent.com/12456965/45078180-9a779280-b0ef-11e8-9a57-f031486155aa.png">

<img width="1261" alt="screen shot 2018-09-05 at 09 39 16" src="https://user-images.githubusercontent.com/12456965/45078173-9186c100-b0ef-11e8-859b-2135c939dc9f.png">

![lumen issue](https://user-images.githubusercontent.com/12456965/45078371-25588d00-b0f0-11e8-8fb2-bdc29be58622.gif)

# Solution or next step
*How could we solve it?*

**Comment by finnfiddle** [comment] 2018-09-18 08:05
duplicate of/same root problem as https://github.com/akvo/akvo-lumen/issues/1650

**Closed by finnfiddle** 2018-09-18 08:05 UTC
Labels: dashboards v2, ready for dev
