### ISSUE TITLE
Split column as a Lumen transform

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#797] opened 2017-06-01 13:45 UTC
# Context

There are a few use cases for allowing splitting columns. 
One of them are cascade questions in Flow. When a Flow form with answers to cascade questions is imported into Lumen, one cell in a dataset will contain multiple answers:

<img width="411" alt="screen shot 2017-06-01 at 15 44 55" src="https://cloud.githubusercontent.com/assets/21127166/26682585/491bb91c-46e1-11e7-8c16-18945273b4de.png">

# Problem or idea
Having several answers in one cell in a Lumen dataset complicates data analysis and visualisation.
It might be possible to solve this problem with the derived column but the solution is non trivial. It would involve multiple steps, which is problematic if not impossible for the majority of partners. Therefore, ideally, the solution to splitting columns should be outside of the derived column functionality. 

# Solution or next step
Just for information, Flow export to excel file handles this cascade problem with splitting columns during export.

**Comment by jonase** [comment] 2017-06-05 06:58
I helped Nikki a similar problem today. She had a cascade with 3 levels and she wanted to extract the second level (Province). We solved this with the following derived column formula:

```js
row['The Cascade Column'].split('|')[1]
```

which successfully derived the Province out of the pipe-separated cascade string.

**Comment by janagombitova** [comment] 2018-10-26 14:19
@tangrammer when we talk about improving the derived column to make it easier for user to use and to build on the multiple value data type what are your thoughts on this specific derived column function? It is one of the most used ones currently.

**Comment by tangrammer** [comment] 2018-10-30 10:38
In relation to better integration with akvo-flow of question.option types, 
Trying to follow the same path as extracting multiple values from caddifsly types, Emmanuel Mulo answered following:

```
[me] can i retrieve the questionOptions linked to question of "OPTION" type?

 https://github.com/akvo/akvo-flow/blob/ffac2098b0e5b66471b65c28aaa3f62999531682/GAE/src/com/gallatinsystems/survey/domain/Question.java#L58 


[Emmanuel] Ahah! So if you check there is a PR on the api repository right now to retrieve question options but for performance reasons we didn’t merge it yet

[Emmanuel]  We need to figure out a way to handle it without degrading the API performance

[me] wow! that's a big coincidence :)
  

[Emmanuel] hehe yes and also an unfortunate one
```

**Comment by tangrammer** [comment] 2018-11-08 12:08
Documentation added to https://github.com/akvo/akvo-lumen/pull/1744 conversation tab

**Comment by janagombitova** [comment] 2018-11-12 15:37
See comment here for some random (meaning I cannot reproduce them twice) issues found during testing on dark lumen test: https://github.com/akvo/akvo-lumen/pull/1744#issuecomment-437919838

**Comment by janagombitova** [comment] 2018-11-15 14:44
Released today so we can close the issue

**Closed by janagombitova** 2018-11-15 14:44 UTC
Labels: ready for testing, transformations

**Comment by Kiarii** [comment] 2018-11-21 09:14
Just had a look at the issue on Jana's request and made some notes, sketches rather.. Have a click and let me know what you think:
https://invis.io/9BP8AI93HRN#/332557374_0-_Visual_Expression
(I was unsure whether to reopen this issue or to create a new one, so I chose to comment instead)
The sketches:
* Reorder and group the transform menu
* Make slight changes to the existing UI
** Split at in place of Separator
** Specify how many new cols will be created and provide naming options for these
* Poses some questions, which need not be answered now
** Shd the new columns appear next to their mother col; the user doesnt have to scroll to the end of a dataset to see the result?
** Do we check that the entered separator character will work after it is entered or do we wait until the user hits the split button?


**
side note: transform operations would ideally be performed on a new screen, where in addition to the content we provide to the user on the side bar editor, we can also provide a preview to show how a split, a merge, an extract, a cluster and edit etc will be performed and what kind of outcome the user can expect. This is for later though

**Comment by janagombitova** [comment] 2018-11-21 10:31
@Kiarii thank you for taking a look at the time. I propose to handle this in a separate issue as we will be improving the front end mostly. Created in the issue linked.
