### ISSUE TITLE
Translate keycloak refresh-token functionality to auth0

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2228] opened 2019-06-24 11:27 UTC
# Context
As auth0 docs [states](https://auth0.com/docs/tokens/refresh-token/current#authentication-methods) :
## A Single-Page Application (normally implementing Implicit Flow) should not ever receive a Refresh Token. 

```
A Single-Page Application (normally implementing Implicit Flow) should not ever receive a Refresh Token. A Refresh Token is essentially a user credential that allows a user to remain authenticated indefinitely. This sensitive information should be stored securely and not exposed client-side in a browser.

If you are implementing an SPA using Implicit Flow and you need to renew a token, the only secure option for doing so is to use Silent Authentication.

```

https://auth0.com/docs/api-auth/tutorials/silent-authentication

# Problem or idea
Currently we are using refresh-tokens when lumen backend talk to flow-api

# Solution or next step
How could we solve it?

**Comment by tangrammer** [comment] 2019-06-27 12:59
Possible option ;) 

1. lumen backend receives a import/update flow http request call with a jwt user token (with user email)
2. lumen uses authorisation server to check that user can import/update flow survey
3. lumen ask auth0 for a machine-to-machine token to communicate with flow https://auth0.com/docs/microsites/call-api/call-api-m2m-app
4. lumen send this machine-to-machine token to flow
5. flow validates machine-to-machine token

**Comment by dlebrero** [comment] 2019-08-14 10:35
We opted for Flow API to trust Lumen, so that it will not expect a JWT token but just prove that Lumen is the one calling it. We will rely on Istio to do it.

For it, we added a new k8s service to flow-api that is only accessible from within the k8s. Lumen should start using this service at "http://flow-api-internal" without any JWT token.

**Comment by tangrammer** [comment] 2019-08-23 12:48
Depends on https://github.com/akvo/akvo-flow-api/issues/178 to be closed

**Comment by tangrammer** [comment] 2019-08-26 09:53
after https://github.com/akvo/akvo-flow-api/commit/2023bc2531ef259847b51c190b212ae70ed59cbf

it can be tested on https://lumen.akvotest.org


Relates to https://github.com/akvo/akvo-flow-api/issues/179

**Comment by janagombitova** [comment] 2019-08-29 13:23
@tangrammer is there anything here I can help with testing? If not and the issue is handled well, then I think we can close it to see what is remaining for the Auth0 work

**Closed** 2019-08-29 15:04 UTC
Labels: Auth0
