### ISSUE TITLE
Restructure Dataset-viewing/editing-screen top menu

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#776] opened 2017-05-29 15:00 UTC
# Context
Atm the Dataset-viewing/editing-screen top menu takes a lot of real estate without providing as much value. 

<img width="1381" alt="screen shot 2017-05-29 at 17 53 03" src="https://cloud.githubusercontent.com/assets/12692444/26554246/d51aa488-4497-11e7-8688-4d3df2cc1f82.png">

The following are not required/implemented so can be removed; however they can be accommodated on the proposed menu in a minimal way
- Row/Col count
- search

# Idea
- We need to make a more focused use of the menu area to support tasks that the user is likely to perform or performs frequently
- Less frequently used Actions should go to the [...] to declutter the menu

# Proposal
![image](https://cloud.githubusercontent.com/assets/12692444/26554308/22479a90-4498-11e7-8ecb-c6442fa10812.png)

- "Dataset Editor" is to be renamed "+ Transform" as proposed in #775

**Comment by loicsans** [comment] 2017-06-08 11:03
Priority: 7
Effort: 3

**Comment by Kiarii** [comment] 2017-06-08 11:09
Sketch the top menu, to accommodate the transform log button and dataset metadata

**Comment by Kiarii** [comment] 2017-06-08 14:50
In maintaining only those parts that are operational, we could start with this; 
- the ordered list as the transform log
- the col / row count introduces an extra hurdle: when to cap as 1k, 1m and so on..

![image](https://user-images.githubusercontent.com/12692444/26934595-78aaa9ae-4c72-11e7-8b6a-43602afef934.png)

**Comment by janagombitova** [comment] 2020-05-27 13:03
Duplicate of #2706

**Closed by janagombitova** 2020-05-27 13:03 UTC
Labels: Good first issue, client, frontend
