### ISSUE TITLE
Double scroll bars when selecting visualisation type 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1737] opened 2018-10-30 09:23 UTC
# Problem or idea
*What is the cause?* 

When selecting a visualisation type you get double scroll bars, vertical and horizontal (not the intended blue scrollbar, which you also get). 

# Solution or next step
How could we solve it?

![screen-shot-20181030-at-09](https://user-images.githubusercontent.com/12456965/47708164-c74ab080-dc2d-11e8-9178-1f44727a6fd2.png)

**Comment by finnfiddle** [comment] 2018-11-27 09:13
I can remove the vertical scrollbar. However, reimplementing the native scrollbars is not a trivial task to get them working nicely across all browsers etc. So instead of replacing the native ones I added the blue indicator. This is so that on macOS - when the scrollbars hide themselves automatically - then you know the scroll position of the container by looking at the blue indicator. If you would like it differently let me know

**Comment by loicsans** [comment] 2018-11-27 09:19
@finnfiddle I actually did reimplement the native scrollbar and removed the vertical scrollbar last week, there's a pull request assigned to you

**Comment by finnfiddle** [comment] 2018-11-27 10:37
So when implementing this feature 2 requirements arose:

1. the user (Jerome) should be able to scroll sideways without a trackpad or mousewheel
2. Jerome should be able to see at all times the scroll position

I dont have any answers but the implementation was the best I could come up with

**Comment by loicsans** [comment] 2018-11-27 10:41
@finnfiddle I don't see the problem, with my implementation not meeting the requirements

**Comment by loicsans** [comment] 2018-11-27 11:33
![nov-27-2018 12-48-08](https://user-images.githubusercontent.com/1717219/49079347-fcf0b280-f248-11e8-8279-c75355199aea.gif)

**Comment by finnfiddle** [comment] 2018-11-27 11:52
@loicsans try on firefox. Firstly, there is no indication of the scroll position. Also the native scrollbars dont appear if i hover so I have no way of scrolling without a trackpad or mousewheel.

**Comment by loicsans** [comment] 2018-12-04 14:43
The vertical scrollbar is addressed, although, we decided that the issue is the choice of layout itself and won't accommodate the addition of more visualisations going forward. 
Therefore fixing the scrollbar isn't worth the effort for now, I'll reopen a design issue concerning the visualisation selector.

**Closed** 2018-12-11 10:43 UTC
Labels: in progress
