### ISSUE TITLE
Regression in user invitation revocation

### ISSUE THREAD

**Issue by peeb** [akvo/akvo-lumen#918] opened 2017-06-30 09:45 UTC
<img width="548" alt="screen shot 2017-06-30 at 11 25 09" src="https://user-images.githubusercontent.com/155294/27730694-1b65be70-5d82-11e7-8c56-ba11cce87ffd.png">

# Solution or next step
Fixed `ConfirmUserAction` modal to display `email` instead of as-yet-undefined `username` .

**Comment by janagombitova** [comment] 2019-01-07 09:37
I could not reproduce this issue as I could not invite a user without defining the email. If anyone knows how to reproduce and check that this is still relevant please do so and reopen the issue. Closing for now

**Closed by janagombitova** 2019-01-07 09:37 UTC
