### ISSUE TITLE
Cannot delete some visualisations

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#335] opened 2016-08-24 13:47 UTC
How to reproduce:
1) In the current dashboard, try to delete the visualisation "Bar None'. 
2) The delete does not succeed, with a 500 internal server error

Expected behaviour:
Visualisation should be deleted.

**Comment by kardan** [comment] 2016-08-25 09:41
I was able to reproduce this on the test instance but have not managed to while running locally. Since we want to use the test instance for demo purpose at the moment I don't want to touch data there too much (and mess up anything). Will look into this after demos.

**Comment by kardan** [comment] 2016-08-26 06:56
Turns out that the db on the test instance have not been created with the correct migrations (since migrations have changed). 

Test instance:
https://gist.github.com/kardan/48f87f9fdbd05483d6718640e1443dec

Local (running develop):
https://gist.github.com/jonase/0c5bd4c16f0df1ff611e35bcf78cf6c5

This should not happen once we go live but until then migrations might change and unless we wipe data as part of deployment it will be difficult to get away from. 

Depending on how valuable the data on the test instance have (for demo purposes) We should either:
-  wipe data and provision a "new" db with current migrations.
- do an ad hoc alter table to add constraint (ON DELETE CASCADE)

**Comment by kardan** [comment] 2016-08-26 11:31
Fixed via deployment

**Closed** 2016-08-26 11:31 UTC
Labels: backlog
