### ISSUE TITLE
Deleting a layer doesn't update the map

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1248] opened 2018-01-30 14:39 UTC
# Context

I experienced the issue in prod environment:

![deleting a layer](https://user-images.githubusercontent.com/21127166/35571951-c87e9a24-05d3-11e8-94d2-ad51a27aac6e.gif)

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by finnfiddle** [comment] 2018-03-05 11:12
cant reproduce - possibly fixed in https://github.com/akvo/akvo-lumen/issues/1215

**Closed by finnfiddle** 2018-03-05 11:12 UTC
Labels: maps
