### ISSUE TITLE
Changing scatter size column gets blank page

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#1901] opened 2019-01-09 16:09 UTC
# Context
<img width="694" alt="screen shot 2019-01-09 at 17 07 45" src="https://user-images.githubusercontent.com/731829/50911954-3c5a1380-1431-11e9-92e3-d6b0dd71f751.png">

# Problem or idea
Selecting a size column breaks the UI (blank page)

# Solution or next step
...

**Comment by finnfiddle** [comment] 2019-02-01 09:49
@tangrammer I cant reproduce - is it still reproducible on your side?

**Comment by tangrammer** [comment] 2019-02-05 09:13
@finnfiddle yep, still happening here. Try to unselect the size value to force the problem

**Comment by finnfiddle** [comment] 2019-02-06 11:44
this should be fixed in https://github.com/akvo/akvo-lumen/pull/1952

**Comment by janagombitova** [comment] 2019-02-20 10:33
no blank pages on dark test. looking good

**Closed by janagombitova** 2019-02-20 10:33 UTC
Labels: bug, ready for testing
