### ISSUE TITLE
Importing dataset/creating visual & dashboard only appears in Library not in collection-library

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2539] opened 2020-02-04 09:35 UTC
# Context
<img width="492" alt="Screenshot 2020-02-04 at 10 32 53" src="https://user-images.githubusercontent.com/731829/73732020-ba264680-4739-11ea-8552-cdd6dc3d73dc.png">
If lumen is importing a dataset (tested from flow), this process/dataset only appears if you click on Library but is not shown on library-collection.
Once that importing process finished and dataset is loaded in lumen, then it's not in the proper place. so if user was in library-collection the dataset only is on Library

# Problem or idea
This data scenario case in client side is not covered

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment] 2020-04-08 11:07
Also reported by Deden via support: https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-320871-from-deden-at-akvo-dot-org

**Comment by janagombitova** [comment] 2020-04-08 11:10
There are two ways to handle this that I can think of and we should apply to all  new datasets, visualisations and dashboards: 
1. If a user imports a dataset/creates a visualisation or dashboard when being in a collection, we automatically add it to the collection. We could ask once the user clicks to create if she wants it to be part of the collection. 
2. We do not allow to import a dataset/create a visualisation or dashboard when in a collection meaning the action buttons are hidden.

**Comment by iperdomo** [comment] 2020-04-08 12:15
Agree with option 1 :+1:, what I'm not sure is about the _asking the user_ part. 
If the user is in the collection and imports a Dataset, it gets automatically _added_ to the collection. (the Dataset is part of the whole library). If it was a _mistake_, the user can remove the Dataset from the collection, right? :thinking:

**Comment by tangrammer** [comment] 2020-04-08 12:19
`the user can remove the Dataset from the collection, right?`  yep

and agree also with the option 1

**Comment by janagombitova** [comment] 2020-04-08 13:24
Then let's go with option1.

**Comment by janagombitova** [comment] 2020-06-22 14:20
Connected to: https://github.com/akvo/akvo-lumen/issues/2691

**Comment by valllllll2000** [comment] 2020-09-29 10:20
I have been trying to add a new dataset to a collection when importing and it does not work. I see an error but if I look in the library the dataset is there so it's a bit confusing the first time, see video:
https://drive.google.com/file/d/1nEpMUpqBI6pxMCBKlFgmHaejWsL3awrN/view?usp=sharing

**Comment by janagombitova** [comment] 2020-12-01 11:37
Making one issue out of all that we have: When a user is in a collection and tries to import a dataset or create a new visualisation or dashboard we want it to show in the collection (and Library) and be part of that collection. 

Closing related issues (and duplicates): 
https://github.com/akvo/akvo-lumen/issues/2691

**Comment by janagombitova** [comment] 2021-06-03 12:02
@melowsoft Hey Anthony I am assigning you this issue as well. It it not a bug, more an implementation we never put in place but quite an annoying thing to users. Juan can explain it more if needed. 

Here is a quick summary: 
In Lumen, you create datasets, visualisations, dashboards. All these by default live in the Library. But a use can create a collection and add her datasets, visualisations, dashboards it a Collection. However, when she is in a Collection and clicks to create a new visualisation, Lumen should create the visualisation, add it to the Library and also to the Collection the user is in.

**Comment by janagombitova** [comment] 2021-06-21 06:20
I was not sure if this issue is fully handled or not, so I tested it on lumen.akvotest.org and it is not working there yet.

**Comment by iperdomo** [comment] 2021-06-21 07:10
@janagombitova I tested importing a dataset (CSV) *inside* a collection in `lumen.akvotest.org` and worked. What type of dataset did you tried?

**Comment by janagombitova** [comment] 2021-06-21 07:14
@iperdomo I just spoke with @melowsoft and indeed handling datasets does work fine. But we also need to handle the creation of visualisations and dashboards. Then the issue will be *fully* handled

**Comment by iperdomo** [comment] 2021-06-21 07:19
I didn't know that the full context of the issue was *all* type of entities. Makes sense to handle the other ones.

**Comment by janagombitova** [comment] 2021-06-23 07:08
@melowsoft Great job! I tested it just now on lumen.akvotest.org and all works really well. 

Can you make one more adjustment? Currently: 
1. I go to a collection
2. I create my visualisation/dataset/dashboard and get the message notification that it was added to my collection
3. Once I am done with my visualisation/dataset/dashboard I go back I land in the Library. But I came from my collection. So it is a bit confusing that now I am in the Library. 

Would it be possible to make sure that if I start from a collection > create something > I go back to the collection I came from?

**Comment by melowsoft** [comment] 2021-06-23 08:27
Yes, it is possible

**Comment by janagombitova** [comment] 2021-06-24 14:07
Done done

**Closed by janagombitova** 2021-06-24 14:07 UTC
Labels: bug, client
