### ISSUE TITLE
Move dataset editor menu to the top

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#2303] opened 2019-09-05 13:27 UTC
# Context
To use the dataset view and editor real estate optimally, it makes sense to move the dataset editor menu to the top.
Currently, we are more or less using the first cols of the screen sub optimally with the rhs of the top row and the second row middle part being left unused, as can be seen in the shot below:
<img width="1330" alt="Screenshot 2019-09-05 at 16 20 07" src="https://user-images.githubusercontent.com/12692444/64345564-46043d00-cff9-11e9-9c49-92ecffa0ccae.png">
 
# Idea
<img width="1349" alt="Screenshot 2019-09-05 at 16 25 52" src="https://user-images.githubusercontent.com/12692444/64345921-db9fcc80-cff9-11e9-97c1-0031cf7e2e53.png">

**Comment by janagombitova** [comment] 2019-09-06 07:06
@Kiarii I do not fully understand the change you propose. What do you mean by **dataset view** and **dataset editor**? Aren't those one thing? From what I see in your mockup, you moved the 'All changed saved' under the dataset title and the 'Transform' and 'Visualise' actions to the right. Thus moving from 2 rows to 1. Do I understand it correctly?  

My questions about the proposal (if I follow it well) are: 
* where did the indication of **the number of columns and rows** go?
* Why did you move the transformation log inbetween the action buttons?
* How will we handle long dataset names in this scenario?

**Comment by Kiarii** [comment] 2019-09-06 08:59
@Jana, thanks for highlighting these. Yes the view and editor are the same thing :) and the proposal is to move from 2 rows to 1. 
- On the col and row count, I am still trying to figure out their placement; we could consider the following: 
<img width="1349" alt="Screenshot 2019-09-06 at 11 56 59" src="https://user-images.githubusercontent.com/12692444/64415307-b4024000-d09d-11e9-90c3-4c6f590f2def.png">

- the log button sits in between the actions because its function focuses on whats in this screen, while the *visualize* sends the user somewhere else..
- Dataset titles, in deed all asset titles, in edit/view, should have a small font than they currently do. It is obvious in respective screens they are the items in view/edit and if we deem it necessary to emphasize them we can instead use font weight and in so doing still have ample area available for long titles.

**Comment by janagombitova** [comment] 2020-05-13 03:25
Duplicate of #776

**Closed by janagombitova** 2020-05-13 03:25 UTC
Labels: Good first issue
