### ISSUE TITLE
Area charts with large values on Y axis get cut off

### ISSUE THREAD

**Issue by bjelkeman** [akvo/akvo-lumen#722] opened 2017-05-11 12:10 UTC
# Context
Creating a chart with a large label on the Y axis can cut off the label displayed. 

# Problem or idea
The text in the Y axis label doesn't seem to be taken into account when placing the chart on the canvas, maybe?

Example: https://demo.akvolumen.org/visualisation/59145131-82e9-4c86-b024-bf47a09b7e84
https://demo.akvolumen.org/s/VrZLYMlHPiY

# Solution or next step
Make the chart aware of the length of the Y axis label.

**Comment by janagombitova** [comment] 2019-01-07 08:43
I could not reproduce this issue. Closing it for now until we have a more recent example

**Closed by janagombitova** 2019-01-07 08:43 UTC
Labels: dashboards
