### ISSUE TITLE
Import into collections, do import but not into collection

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#3063] opened 2020-11-30 15:18 UTC
# Context
If the user have selected a collection and tries to import a dataset it's expected that the dataset get added to the current collection.

# Problem or idea
At the moment the dataset is imported into the Library but an error is generated and the dataset is not added to the collection. No errors are generated at the backend.

![Screenshot 2020-11-30 at 16 17 34](https://user-images.githubusercontent.com/31837/100627782-b64a5d00-3327-11eb-92a5-f9dd613b6ebd.png)

# Solution or next step
?

**Comment by janagombitova** [comment] 2020-12-01 11:37
Duplicate of #2539

**Closed by janagombitova** 2020-12-01 11:37 UTC
