### ISSUE TITLE
An option to print a visualisation/dashboard

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1095] opened 2017-10-02 15:07 UTC
# Context
A few partners have shown interest in exporting a whole dashboard or a single visualisation in a printable format. 
Many institutions still consume information in the form of reports, so we should cater to this large group of users too.

According to Geert's stakeholder analysis, national governments and donors prefer to consume data in a report format:

<img width="920" alt="screen shot 2017-10-02 at 17 05 50" src="https://user-images.githubusercontent.com/21127166/31084188-0691dc52-a794-11e7-9c2c-1c143a994f5e.png">

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by nadiagorchakova** [comment] 2018-03-27 12:41
printing out visualisations/dashboards or downloading them in a printable format is something I hear a lot from partners @finnfiddle 
it's a bit problematic at the moment though as charts loose interactivity (and values with it) when printed out.

**Comment by finnfiddle** [comment] 2018-07-26 14:01
duplicate of #952

**Closed by finnfiddle** 2018-07-26 14:01 UTC
Labels: dashboards v2
