### ISSUE TITLE
Colour picker jumps out of view

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1572] opened 2018-07-19 14:49 UTC
# Context
I'm working on a dashboard demo example now, so while experimenting with different visualisations, I stumbled upon an interesting case with colour picker.

# Problem or idea
When working with split bar chart, the colour picker jumps out of view while customising colours for split bars:

![ezgif com-gif-maker 21](https://user-images.githubusercontent.com/21127166/42950055-7c5db7bc-8b73-11e8-8434-47d3e90fd7ac.gif)

Disclaimer: I'm not sure if it's significant or not, but I applied a dataset filter prior to working with colour picker. I filtered for just one bar to be displayed on the graph.

# Solution or next step
How could we solve it?

**Comment by nadiagorchakova** [comment] 2018-07-19 15:00
Can confirm that I can replicate the issue on any *split* bar chart in production:

<img width="1270" alt="screen shot 2018-07-19 at 16 58 50" src="https://user-images.githubusercontent.com/21127166/42950852-2a543426-8b75-11e8-8b7b-67bb7e2d1d2c.png">

**Comment by finnfiddle** [comment] 2018-08-17 09:26
I cant reproduce. Need a link to an example where this is happening @nadiagorchakova

**Comment by janagombitova** [comment] 2018-08-17 09:39
@finnfiddle I could not either and tried in Chrome, Firefox and Safari. Let's close it for now.

**Closed by janagombitova** 2018-08-17 09:39 UTC
Labels: cant reproduce, ready for dev
