### ISSUE TITLE
% values in pie and donut charts 

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#600] opened 2017-02-17 16:44 UTC
# Context

Currently, it's only possible to see count for pie chart slices:

<img width="1277" alt="screen shot 2017-02-17 at 17 39 22" src="https://cloud.githubusercontent.com/assets/21127166/23074122/29753ade-f538-11e6-8469-877a66d41817.png">

# Problem or idea

Karolina suggested that sometimes it's more useful to see % of each slice in relation to the whole data sample.

# Solution or next step

Perhaps we should have an option in pie chart editor to pick whether pie chart should display count or % for each slice.

**Comment by mtwestra** [comment] 2017-02-21 13:41
Repeated in #608, so closing that one.

One option is to show the percentage value in brackets as part of what is shown on hover. So in the above example, we would show '687 (67.3%)'

**Comment by gabemart** [comment] 2017-02-21 15:47
This has actually been the intended behaviour all along -- the fact that it is not showing currently is due to a bug in a recent refactor of the pie chart spec.

**Comment by gabemart** [comment] 2017-02-28 09:20
Closed via #612

**Closed by gabemart** 2017-02-28 09:20 UTC
Labels: needs review
