### ISSUE TITLE
When changing title of a visualisation, 'unsaved changes' should display

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#552] opened 2017-02-07 14:07 UTC
### How to reproduce
* create a visualisation
* start editing the name of the visualisation
=> the status indicator still displays 'All changes saved'

### Expected behaviour
If I change the name of the visualisation, I would expect that it shows 'Unsaved changes', so I remember to click the save button.

**Comment by gabemart** [comment] 2017-02-08 08:51
The issue is that the changes only propagate on the "blur" event of the title input - i.e. when the user finishes editing the title, rather than begins editing the title

I agree that it's incorrect to show the "changes saved" message when editing is in progress

**Comment by mtwestra** [comment] 2017-02-08 10:50
@gabe, this solution sounds fine to me.

**Comment by nadiagorchakova** [comment] 2018-04-03 14:59
I think this issue has been fixed already?
<img width="1271" alt="screen shot 2018-04-03 at 16 58 37" src="https://user-images.githubusercontent.com/21127166/38257307-46acf0a4-3760-11e8-9e33-0d07f8207909.png">

will close it if none complains..

**Closed** 2018-04-03 15:00 UTC
Labels: triaged
