### ISSUE TITLE
Pivot table extra white space 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1640] opened 2018-09-05 07:46 UTC
# Problem or idea
*What is the cause?*

Molo created a dashboard where he added a map and a pivot table in one row. In the shared dashboard they appeared next to each other. Then he added a text box above the pivot table. In the editor everything was arranged nicely next to each other, but in the shared link the pivot table shows under the map. There seems to be this extra white space under the pivot table visualisation in the shared link that then makes the pivot table not fit in the row next to the map. So the alignment Molo set on his dashboard does not reflect in the shared link. 

Example dashboard on demo: https://demo.akvolumen.org/s/gXwCdv1tp-g
![lumen issue](https://user-images.githubusercontent.com/12456965/45078510-86806080-b0f0-11e8-8d58-cb7e8f3d446a.gif)

I tried making the map visualisation longer to expand the row height hoping the pivot table will stay next to the map in the shared link but that did not help. 

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment] 2018-09-06 06:16
Created via Reamaze:

Link: /admin/conversations/akvolumen-support-request-number-146199-from-andrew-at-akvo-dot-org

**Comment by finnfiddle** [comment] 2018-09-18 08:04
duplicate of https://github.com/akvo/akvo-lumen/issues/1650

**Closed** 2018-09-18 08:04 UTC
Labels: dashboards v2, ready for dev
