### ISSUE TITLE
Update client deps (estimate: 2)

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#424] opened 2016-11-15 05:54 UTC

**Comment by jonase** [comment] 2016-12-01 14:23
will push this to the next milestone, there are quite a few things to consider and it's a bit risky to blindly update this close to the end of the milestone. Will look at it early next week instead.

**Comment by jonase** [comment] 2016-12-05 10:56
@gabemart 

- [ ] Remove (and resolve) eslint rules `class-methods-use-this` and `no-plusplus`
- [ ] Look into why maps breaks with latest `leaflet` and `react-leaflet` versions

**Comment by gabemart** [comment] 2016-12-05 12:34
I've investigated the maps/leaflet problem.

The basic problem is that the images for the markers are failing to load.

Lealeft did make [some changes to image loading in 1.0.0 that were causing errors for some](https://github.com/Leaflet/Leaflet/issues/4849), but these are supposed to be fixed in 1.0.1 - but not for us, so I suspect our issue is related but distinct.

I think our issue is https://github.com/Leaflet/Leaflet/issues/4968

I suspected it might be caused by our use of a webpack loader to create data-urls for small images, but switching to regular file loading for images doesn't fix the problem.

It would be easy to go pretty far down the rabbit hole on this, but my feeling is that we can afford to wait another release cycle before investigating further. I think there's a good chance of this being fixed soonish in leaflet. We could add a workaround now, but if it gets fixed upstream we would just have to remove the workaround again.

I vote we leave leaflet and react-leaflet at their current semvers for one more cycle.

**Closed** 2016-12-07 14:34 UTC
Labels: ready
